### ISSUE TITLE
Request for Additional Instructions to Reproduce Paper Results

### ISSUE THREAD

**Issue by gpzlx1** [RC4ML/Legion#1]
Hello,

I've noticed that this excellent work has achieved two badges, "available" and "functional," in ATC23. However, in my opinion, the current repository lacks sufficient instructions to reach the target. Could you please provide the link to the artifacts in ATC23 or add more instructions to aid in reproducing the paper's results?

Best regards.

**Comment by JIESUN233** [comment]
Hi, I update the instructions in the repo.
