### ISSUE TITLE
Synchronization for intra-batch operations

### ISSUE THREAD

**Issue by AKKamath** [RC4ML/Legion#6]
Hi, thanks for open-sourcing this code, it's very well-written!

From my understanding of the sampling server logic, the feature cache lookup operations should happen after the BatchGenerate/RandomSample, because the sampled_ids being looked up in the feature cache are generated by the batch/sampling operation. 

The code seems to indicate these operations happen on separate streams (https://github.com/RC4ML/Legion/blob/adbf3ca8b6d1e4c414e99f6751638f79012889fd/sampling_server/src/engine/server.cu#L258) and I could not find any synchronization between these operations. 

The closest synchronization I found was at line 313 (https://github.com/RC4ML/Legion/blob/adbf3ca8b6d1e4c414e99f6751638f79012889fd/sampling_server/src/engine/server.cu#L313), which seemed to force stream 0 (the sampling stream) to wait until the previous cache lookup operation was completed. My understanding is that it should be the opposite where the cache lookup stream (stream 1) waits for sampling to complete.

Am I misunderstanding something? 

Thanks again

**Comment by JIESUN233** [comment]
Thanks for your comments. You're right. This seems to be a mistake during code refactoring. The line 313 should be cudaStreamWaitEvent(streams_[i / INTRABATCH_CON], events_[i / INTRABATCH_CON * INTRABATCH_CON], 0);

**Comment by AKKamath** [comment]
I'm still a bit confused about this. Shouldn't it be:
`cudaStreamWaitEvent(streams_[i%INTRABATCH_CON], events_[i / INTRABATCH_CON * INTRABATCH_CON], 0);`
That way the upcoming operation's stream waits for the sampling event to complete first?

**Comment by JIESUN233** [comment]
yes, it should be cudaStreamWaitEvent(streams_[i%INTRABATCH_CON], events_[i / INTRABATCH_CON * INTRABATCH_CON], 0);

**Comment by AKKamath** [comment]
Thanks for the quick replies. This clarifies things. Thanks again for open-sourcing your code!
